# Xarray-Gallery

根据日常使用情况，本文罗列一些用Xarray的例子。

## 读取多个 nc 文件

gallery-data文件夹下面 14303200 和 14306340 下面共4个nc文件，读取到一个xarray-dataset中，这两个文件夹的数据分别属于 14303200 和 14306340 这两个对象。

xarray读取多文件的函数open_mfdataset 需要同时指定多文件，所以为了读取不同的文件夹下的文件，需要首先一次性将符合条件的数据读取出来。

或者同一个文件夹读取多个文件，然后再将多个dataset连接起来（这种更灵活一些）。

主要参考以下资料：

- [how to open multiple netcdf files stored in multiple folders Python](https://stackoverflow.com/questions/50096170/how-to-open-multiple-netcdf-files-stored-in-multiple-folders-python)
- [python-xarray: open_mfdataset concat along two dimensions](https://stackoverflow.com/questions/47545138/python-xarray-open-mfdataset-concat-along-two-dimensions)

In [1]:
import glob

# Get a list of all .nc files available in different folders
filenames = glob.glob("gallery-data/*/*.nc")
filenames

['gallery-data\\14303200\\14303200_1990_nomask.nc',
 'gallery-data\\14303200\\14303200_1991_nomask.nc',
 'gallery-data\\14306340\\14306340_1990_nomask.nc',
 'gallery-data\\14306340\\14306340_1991_nomask.nc']

In [3]:
import xarray as xr
dsmerged = xr.open_mfdataset(filenames)

In [4]:
dsmerged

<xarray.Dataset>
Dimensions:  (time: 730, x: 13, y: 11)
Coordinates:
  * x        (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time     (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:00:00
  * y        (y) float64 548.0 547.0 546.0 545.0 ... 440.0 439.0 438.0 437.0
Data variables:
    dayl     (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    lat      (time, y, x) float64 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    lon      (time, y, x) float64 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    prcp     (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    srad     (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    swe      (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    tmax     (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    tmin     (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
    vp       (time, y, x) float32 dask.array<chunksize=(365, 5, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

先和单独读取文件的数据比较下，看看结果对不对

In [62]:
single_path = "gallery-data/14303200/14303200_1990_nomask.nc"
year1990_data = xr.open_dataset(single_path)

In [63]:
year1990_data

<xarray.Dataset>
Dimensions:  (time: 365, x: 6, y: 5)
Coordinates:
  * time     (time) datetime64[ns] 1990-01-01T12:00:00 ... 1990-12-31T12:00:00
  * y        (y) float32 548.0 547.0 546.0 545.0 544.0
  * x        (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
Data variables:
    dayl     (time, y, x) float32 ...
    lat      (y, x) float64 ...
    lon      (y, x) float64 ...
    prcp     (time, y, x) float32 ...
    srad     (time, y, x) float32 ...
    swe      (time, y, x) float32 ...
    tmax     (time, y, x) float32 ...
    tmin     (time, y, x) float32 ...
    vp       (time, y, x) float32 ...
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

可以看到因为x和y的坐标在两个文件夹下的nc文件里是不同的，所以当一次性读取多文件的时候，是会把两个文件的x和y合起来的，这就会造成有很多NaN值的出现，因为每个nc文件都只在自己对应的x和y坐标下才有值。

这是需要**特别注意**的！所以对于文件内容坐标有很多不同的情况，要慎重使用 open_mfdataset 函数。

这里给出的例子重点是为了记录使用open_mfdataset函数读取多文件数据，所以下面就暂时不再多考虑这一情况了。

上面的方式比较适合同一类型的在不同文件夹下的文件，如果不同文件夹下内容有些不同，需要一个维度标注出来，还是下面的方式更方便一些。

In [9]:
import os
import pandas as pd
import xarray as xr

dir_list = ["14303200","14306340"]
ens_list = []
for num in range(len(dir_list)):
    ens = dir_list[num]
    ens_list.append(xr.open_mfdataset(os.path.join("gallery-data", ens, '*.nc')))
new_dim = pd.Index(dir_list)
# dim的值如果是新维度，会增加到第一个维度上
ds = xr.concat(ens_list, dim=new_dim)

In [10]:
ens_list

[<xarray.Dataset>
 Dimensions:  (time: 730, x: 6, y: 5)
 Coordinates:
   * time     (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:00:00
   * y        (y) float32 548.0 547.0 546.0 545.0 544.0
   * x        (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
 Data variables:
     dayl     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     lat      (time, y, x) float64 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     lon      (time, y, x) float64 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     prcp     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     srad     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     swe      (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     tmax     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     tmin     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     vp       (

In [11]:
ds

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 730, x: 13, y: 11)
Coordinates:
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lat         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lon         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

看看合并之后的数据是不是仍能顺利地索引到正确的数据。

比如只取出第一个文件夹下读出的内容，即 concat_dim 值为"14303200"的。

In [14]:
ds.sel(concat_dim="14303200")

<xarray.Dataset>
Dimensions:     (time: 730, x: 13, y: 11)
Coordinates:
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:0...
    concat_dim  <U8 '14303200'
Data variables:
    dayl        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    lat         (time, y, x) float64 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    lon         (time, y, x) float64 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    prcp        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    srad        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    swe         (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    tmax        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    tmin        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    vp          (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

如前面所述，concatenate后x和y是有所变化的，所以直接判断肯定是不相等。不过当做减法时，是在对应坐标上做运算，所以从具体数据上看，是一致的：

In [29]:
(ds.sel(concat_dim="14303200").swe-(ens_list[0].swe)).values

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 

可以看到做减法是在x和y对应坐标上做的：

In [64]:
(ds.sel(concat_dim="14303200").swe-(ens_list[0].swe)).values.shape

(730, 5, 6)

稍微复杂一点，比如只选择两个文件夹1990年的那些nc文件，则可以利用文件名索引：

In [30]:
ens_list_1990 = []
for num in range(len(dir_list)):
    ens_1990 = dir_list[num]
    # 只要文件名称对应就行了    
    ens_list_1990.append(xr.open_mfdataset(os.path.join("gallery-data", ens_1990, '*_1990_*.nc')))
# dim的值如果是新维度，会增加到第一个维度上
ds_1990 = xr.concat(ens_list_1990, dim=new_dim)

In [31]:
ds_1990

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 365, x: 13, y: 11)
Coordinates:
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1990-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lat         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    lon         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

如果需要具体到内部的日期，可以采用索引的方式（参考了[这里](https://stackoverflow.com/questions/51976126/subset-an-xarray-dataset-or-data-array-in-the-time-dimension)），注意是闭区间：

In [60]:
ds_1990.sel(time=slice('1990-03-01', '1990-03-05'))

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 5, x: 13, y: 11)
Coordinates:
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time        (time) datetime64[ns] 1990-03-01T12:00:00 ... 1990-03-05T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    lat         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    lon         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

再比如如果有多年数据，只允许选择1990和1991的，可以这样：

In [57]:
years = ["1990","1991"]
ens_list_19901991 = []
for num in range(len(dir_list)):
    ens_19901991 = dir_list[num]
    name_lst=[]
    for name in glob.glob(os.path.join("gallery-data", ens_19901991,'*.nc')):
        if name.split("_")[1] in years:
            name_lst.append(name)
    # 只要文件名称对应就行了    
    ens_list_19901991.append(xr.open_mfdataset(name_lst))
# dim的值如果是新维度，会增加到第一个维度上
ds_19901991 = xr.concat(ens_list_19901991, dim=new_dim)

In [58]:
ds_19901991

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 730, x: 13, y: 11)
Coordinates:
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lat         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lon         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

## xarray与pandas和numpy的转换

xarray的数据是懒加载地，通常我们还是需要把数据取出来用，有时候需要将数据转换为pandas DataFrame或者numpy array或者torch的tensor等。

比如想要取出 dayl, prcp 的值，并组成一个numpy array

In [67]:
ds_19901991[['dayl', 'prcp']]

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 730, x: 13, y: 11)
Coordinates:
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

dataset可以转成dataarray，此数据集的数据变量将相互广播并沿新数组的第一个轴堆叠。此数据集的所有坐标将保持。

In [71]:
ds_trans_origin = ens_list[0]

In [74]:
ds_dataarray = ds_trans_origin[['dayl', 'prcp']].to_array()

In [75]:
ds_dataarray

<xarray.DataArray 'stack-65bd9e2feb52428106a38ef2695943bb' (variable: 2, time: 730, y: 5, x: 6)>
dask.array<stack, shape=(2, 730, 5, 6), dtype=float32, chunksize=(1, 365, 5, 6), chunktype=numpy.ndarray>
Coordinates:
  * time      (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:00:00
  * y         (y) float32 548.0 547.0 546.0 545.0 544.0
  * x         (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
  * variable  (variable) <U4 'dayl' 'prcp'
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

dataarray可以转成numpy的array，直接取values即可。可以看到维度是保持顺序的。

In [78]:
ds_dataarray.values.shape

(2, 730, 5, 6)

当选择的变量对应的数据的维度一致时，可以直接转为dataframe

In [73]:
ds_trans_origin[['dayl', 'prcp']].to_dataframe()

dayl   prcp
time                x        y                         
1990-01-01 12:00:00 -1739.25 548.0  30980.070312  15.50
                             547.0  30980.070312  15.11
                             546.0  31006.230469  14.86
                             545.0  31006.230469  14.02
                             544.0  31006.230469  13.97
...                                          ...    ...
1991-12-31 12:00:00 -1734.25 548.0  30932.660156   0.00
                             547.0  30932.660156   0.00
                             546.0  30932.660156   0.00
                             545.0  30932.660156   0.00
                             544.0  30958.929688   0.00

[21900 rows x 2 columns]

## DataArray基本运算

对 xarray 中 DataArray做计算时, 默认的是按照维度名字匹配的, 这里以乘法为例，看下面的例子.

In [10]:
import xarray as xr
x = xr.DataArray(
     [[1.0, 2.0], [3.0, 5.0]],
     dims=("lat", "lon"),
     coords={"lat": [35.0, 40.0], "lon": [100.0, 120.0]},
     name="var1",
)
x

<xarray.DataArray 'var1' (lat: 2, lon: 2)>
array([[1., 2.],
       [3., 5.]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0

In [11]:
t = xr.DataArray([0.1,0.2,0.3], dims="time", coords={"time": [1, 2, 3]}, name="var2")
t

<xarray.DataArray 'var2' (time: 3)>
array([0.1, 0.2, 0.3])
Coordinates:
  * time     (time) int32 1 2 3

In [14]:
y = x * t
y

<xarray.DataArray (lat: 2, lon: 2, time: 3)>
array([[[0.1, 0.2, 0.3],
        [0.2, 0.4, 0.6]],

       [[0.3, 0.6, 0.9],
        [0.5, 1. , 1.5]]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0
  * time     (time) int32 1 2 3

可以看到上述计算中, 乘积是执行的笛卡尔积, 因为没有维度对应上. 再看一个例子

In [15]:
z = x * y
z

<xarray.DataArray (lat: 2, lon: 2, time: 3)>
array([[[0.1, 0.2, 0.3],
        [0.4, 0.8, 1.2]],

       [[0.9, 1.8, 2.7],
        [2.5, 5. , 7.5]]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0
  * time     (time) int32 1 2 3

In [16]:
x

<xarray.DataArray 'var1' (lat: 2, lon: 2)>
array([[1., 2.],
       [3., 5.]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0

可以看到, lat和lon一致的地方对应相乘; 关于时间维, 相当于在x上执行了广播运算. 也就是说相当于 x * y.isel(time=0),  x * y.isel(time=1),  x * y.isel(time=2)

In [21]:
x * y.isel(time=0)

<xarray.DataArray (lat: 2, lon: 2)>
array([[0.1, 0.4],
       [0.9, 2.5]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0
    time     int32 1