# Xarray-Gallery

根据日常使用情况，本文罗列一些用Xarray的例子。

## 读取多个 nc 文件

gallery-data文件夹下面 14303200 和 14306340 下面多个nc文件，读取到一个xarray-dataset中，这两个文件夹的数据分别属于 14303200 和 14306340 这两个对象。

xarray读取多文件的函数open_mfdataset 需要同时指定多文件，所以为了读取不同的文件夹下的文件，需要首先一次性将符合条件的数据读取出来。

或者同一个文件夹读取多个文件，然后再将多个dataset连接起来（这种更灵活一些）。

主要参考以下资料：

- [how to open multiple netcdf files stored in multiple folders Python](https://stackoverflow.com/questions/50096170/how-to-open-multiple-netcdf-files-stored-in-multiple-folders-python)
- [python-xarray: open_mfdataset concat along two dimensions](https://stackoverflow.com/questions/47545138/python-xarray-open-mfdataset-concat-along-two-dimensions)

In [1]:
import glob

# Get a list of all .nc files available in different folders
filenames = glob.glob("gallery-data/*/*.nc")
filenames

['gallery-data\\14303200\\14303200_1990_nomask.nc',
 'gallery-data\\14303200\\14303200_1991_nomask.nc',
 'gallery-data\\14303200\\14303200_1995_nomask.nc',
 'gallery-data\\14303200\\14303200_1996_nomask.nc',
 'gallery-data\\14303200\\14303200_1997_nomask.nc',
 'gallery-data\\14306340\\14306340_1990_nomask.nc',
 'gallery-data\\14306340\\14306340_1991_nomask.nc',
 'gallery-data\\14306340\\14306340_1995_nomask.nc',
 'gallery-data\\14306340\\14306340_1996_nomask.nc',
 'gallery-data\\14306340\\14306340_1997_nomask.nc']

In [2]:
import xarray as xr
dsmerged = xr.open_mfdataset(filenames)

In [3]:
dsmerged

<xarray.Dataset>
Dimensions:  (y: 11, time: 1825, x: 13)
Coordinates:
  * y        (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * time     (time) datetime64[ns] 1990-01-01T12:00:00 ... 1997-12-31T12:00:00
  * x        (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
Data variables:
    dayl     (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    lat      (time, y, x) float64 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    lon      (time, y, x) float64 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    prcp     (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    srad     (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    swe      (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    tmax     (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    tmin     (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
    vp       (time, y, x) float32 dask.array<chunksize=(365, 11, 7), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.54773771920362
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.77675e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1776.75   436.5  -1769.75   442.5 ]

先和单独读取文件的数据比较下，看看结果对不对

In [4]:
single_path = "gallery-data/14303200/14303200_1990_nomask.nc"
year1990_data = xr.open_dataset(single_path)

In [5]:
year1990_data

<xarray.Dataset>
Dimensions:  (time: 365, y: 5, x: 6)
Coordinates:
  * time     (time) datetime64[ns] 1990-01-01T12:00:00 ... 1990-12-31T12:00:00
  * y        (y) float32 548.0 547.0 546.0 545.0 544.0
  * x        (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
Data variables:
    dayl     (time, y, x) float32 ...
    lat      (y, x) float64 ...
    lon      (y, x) float64 ...
    prcp     (time, y, x) float32 ...
    srad     (time, y, x) float32 ...
    swe      (time, y, x) float32 ...
    tmax     (time, y, x) float32 ...
    tmin     (time, y, x) float32 ...
    vp       (time, y, x) float32 ...
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

可以看到因为x和y的坐标在两个文件夹下的nc文件里是不同的，所以当一次性读取多文件的时候，是会把两个文件的x和y合起来的，这就会造成有很多NaN值的出现，因为每个nc文件都只在自己对应的x和y坐标下才有值。

这是需要**特别注意**的！所以对于文件内容坐标有很多不同的情况，要慎重使用 open_mfdataset 函数。

这里给出的例子重点是为了记录使用open_mfdataset函数读取多文件数据，所以下面就暂时不再多考虑这一情况了。

上面的方式比较适合同一类型的在不同文件夹下的文件，如果不同文件夹下内容有些不同，需要一个维度标注出来，还是下面的方式更方便一些。

In [6]:
import os
import pandas as pd
import xarray as xr

dir_list = ["14303200","14306340"]
ens_list = []
for num in range(len(dir_list)):
    ens = dir_list[num]
    ens_list.append(xr.open_mfdataset(os.path.join("gallery-data", ens, '*.nc')))
new_dim = pd.Index(dir_list)
# dim的值如果是新维度，会增加到第一个维度上
ds = xr.concat(ens_list, dim=new_dim)

In [7]:
ens_list

[<xarray.Dataset>
 Dimensions:  (time: 1825, y: 5, x: 6)
 Coordinates:
   * time     (time) datetime64[ns] 1990-01-01T12:00:00 ... 1997-12-31T12:00:00
   * y        (y) float32 548.0 547.0 546.0 545.0 544.0
   * x        (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
 Data variables:
     dayl     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     lat      (time, y, x) float64 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     lon      (time, y, x) float64 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     prcp     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     srad     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     swe      (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     tmax     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     tmin     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
     vp       

In [8]:
ds

<xarray.Dataset>
Dimensions:     (y: 11, x: 13, concat_dim: 2, time: 1825)
Coordinates:
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1997-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lat         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lon         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

看看合并之后的数据是不是仍能顺利地索引到正确的数据。

比如只取出第一个文件夹下读出的内容，即 concat_dim 值为"14303200"的。

In [9]:
ds.sel(concat_dim="14303200")

<xarray.Dataset>
Dimensions:     (y: 11, x: 13, time: 1825)
Coordinates:
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1997-12-31T12:0...
    concat_dim  <U8 '14303200'
Data variables:
    dayl        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    lat         (time, y, x) float64 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    lon         (time, y, x) float64 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    prcp        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    srad        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    swe         (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    tmax        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    tmin        (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
    vp          (time, y, x) float32 dask.array<chunksize=(365, 11, 13), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

如前面所述，concatenate后x和y是有所变化的，所以直接判断肯定是不相等。不过当做减法时，是在对应坐标上做运算，所以从具体数据上看，是一致的：

In [10]:
(ds.sel(concat_dim="14303200").swe-(ens_list[0].swe)).values

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 

可以看到做减法是在x和y对应坐标上做的：

In [11]:
(ds.sel(concat_dim="14303200").swe-(ens_list[0].swe)).values.shape

(1825, 5, 6)

稍微复杂一点，比如只选择两个文件夹1990年的那些nc文件，则可以利用文件名索引：

In [12]:
ens_list_1990 = []
for num in range(len(dir_list)):
    ens_1990 = dir_list[num]
    # 只要文件名称对应就行了    
    ens_list_1990.append(xr.open_mfdataset(os.path.join("gallery-data", ens_1990, '*_1990_*.nc')))
# dim的值如果是新维度，会增加到第一个维度上
ds_1990 = xr.concat(ens_list_1990, dim=new_dim)

In [13]:
ds_1990

<xarray.Dataset>
Dimensions:     (y: 11, x: 13, concat_dim: 2, time: 365)
Coordinates:
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1990-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lat         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    lon         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

再比如如果只允许选择1990和1991的，可以这样：

In [14]:
years = ["1990","1991"]
ens_list_19901991 = []
for num in range(len(dir_list)):
    ens_19901991 = dir_list[num]
    name_lst=[]
    for name in glob.glob(os.path.join("gallery-data", ens_19901991,'*.nc')):
        if name.split("_")[1] in years:
            name_lst.append(name)
    # 只要文件名称对应就行了    
    ens_list_19901991.append(xr.open_mfdataset(name_lst))
# dim的值如果是新维度，会增加到第一个维度上
ds_19901991 = xr.concat(ens_list_19901991, dim=new_dim)

In [15]:
ds_19901991

<xarray.Dataset>
Dimensions:     (y: 11, x: 13, concat_dim: 2, time: 730)
Coordinates:
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lat         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    lon         (concat_dim, time, y, x) float64 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

## xarray中的索引

根据[文档介绍](https://xarray.pydata.org/en/stable/user-guide/indexing.html#indexing)，xarray中dataset和dataarray的索引形式有几种：

|Dimension lookup|Index lookup|DataArray syntax|Dataset syntax|
|-|-|-|-|
|Positional|By integer|da[:, 0]|not available|
|Positional|By label|da.loc[:, 'IA']|not available|
|By name|By integer|da.isel(space=0) or da[dict(space=0)]|ds.isel(space=0) or ds[dict(space=0)]|
|By name|By label|da.sel(space='IA') or da.loc[dict(space='IA')]|ds.sel(space='IA') or ds.loc[dict(space='IA')]|

简单归纳下，Dataset只能用name来进行dimension索引，DataArray适合各种针对 dimension 和index的索引。

比如下面要索引日期，注意是闭区间：

In [16]:
ds_1990.sel(time=slice('1990-03-01', '1990-03-05'))

<xarray.Dataset>
Dimensions:     (y: 11, x: 13, concat_dim: 2, time: 5)
Coordinates:
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time        (time) datetime64[ns] 1990-03-01T12:00:00 ... 1990-03-05T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    lat         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    lon         (concat_dim, y, x) float64 dask.array<chunksize=(1, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 5, 11, 13), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

可以看到如果想要对xarray dataset的所有dataarray执行同样的位置索引是没有直接的索引办法的，这时候可以考虑生成一个DataArray的mask，然后结合where()函数使用，比如想要 y在[1,4]之间，x在[2,6]之间的。

In [17]:
import numpy as np
_mask = np.full([11,13], False)
_mask[1:4, 2:6] = True
_mask

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False,  True,  True,  True,  True, False, False, False,
        False, False, False, False],
       [False, False,  True,  True,  True,  True, False, False, False,
        False, False, False, False],
       [False, False,  True,  True,  True,  True, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False],
       [False, False, False,

In [18]:
# 加上坐标系
coords = {"y": ds_1990.coords["y"], "x": ds_1990.coords["x"]}
coords

{'y': <xarray.DataArray 'y' (y: 11)>
 array([437., 438., 439., 440., 441., 442., 544., 545., 546., 547., 548.])
 Coordinates:
   * y        (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
 Attributes:
     units:          km
     long_name:      y coordinate of projection
     standard_name:  projection_y_coordinate,
 'x': <xarray.DataArray 'x' (x: 13)>
 array([-1776.25, -1775.25, -1774.25, -1773.25, -1772.25, -1771.25, -1770.25,
        -1739.25, -1738.25, -1737.25, -1736.25, -1735.25, -1734.25])
 Coordinates:
   * x        (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
 Attributes:
     units:          km
     long_name:      x coordinate of projection
     standard_name:  projection_x_coordinate}

In [19]:
# 生成xarray DataArray
mask = xr.DataArray(_mask, coords, dims=("y", "x"))

In [20]:
# 利用where，联合mask 截取想要位置的数据
ds_1990_masked = ds_1990.where(mask, drop=True)
ds_1990_masked

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 365, y: 3, x: 4)
Coordinates:
  * y           (y) float64 438.0 439.0 440.0
  * x           (x) float64 -1.774e+03 -1.773e+03 -1.772e+03 -1.771e+03
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1990-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
    lat         (concat_dim, y, x) float64 dask.array<chunksize=(1, 3, 4), meta=np.ndarray>
    lon         (concat_dim, y, x) float64 dask.array<chunksize=(1, 3, 4), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
    srad        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
    swe         (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
    tmax        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
    tmin        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
    vp          (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 3, 4), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

## 插值

上面用到的实例数据来自daymet，daymet数据在闰年也只有365天数据，12月31日那天是直接被忽略掉的，为了保持使用时的完整性和便利性，考虑在闰年的最后一天插值该时间序列数据。

下面先从简单的例子开始。主要参考了：[xarray User Guide / Interpolating data](https://xarray.pydata.org/en/stable/user-guide/interpolation.html)

In [21]:
import numpy as np
import xarray as xr

In [22]:
da = xr.DataArray(
    np.sin(0.3 * np.arange(12).reshape(4, 3)),
    [("time", np.arange(4)), ("space", [0.1, 0.2, 0.3])],
)
da

<xarray.DataArray (time: 4, space: 3)>
array([[ 0.        ,  0.29552021,  0.56464247],
       [ 0.78332691,  0.93203909,  0.99749499],
       [ 0.97384763,  0.86320937,  0.67546318],
       [ 0.42737988,  0.14112001, -0.15774569]])
Coordinates:
  * time     (time) int32 0 1 2 3
  * space    (space) float64 0.1 0.2 0.3

插值的方式和索引的方式是类似的，下面是索引

In [23]:
da.sel(time=3)

<xarray.DataArray (space: 3)>
array([ 0.42737988,  0.14112001, -0.15774569])
Coordinates:
    time     int32 3
  * space    (space) float64 0.1 0.2 0.3

现在在第2和3之间时段之间插值，也就是第三行和第四行之间：

In [24]:
da.interp(time=2.5)

<xarray.DataArray (space: 3)>
array([0.70061376, 0.50216469, 0.25885874])
Coordinates:
  * space    (space) float64 0.1 0.2 0.3
    time     float64 2.5

也可以像索引那样接受一个array-like的参数

In [25]:
da.sel(time=[2, 3])

<xarray.DataArray (time: 2, space: 3)>
array([[ 0.97384763,  0.86320937,  0.67546318],
       [ 0.42737988,  0.14112001, -0.15774569]])
Coordinates:
  * time     (time) int32 2 3
  * space    (space) float64 0.1 0.2 0.3

In [26]:
da.interp(time=[2.5, 3.5])

<xarray.DataArray (time: 2, space: 3)>
array([[0.70061376, 0.50216469, 0.25885874],
       [       nan,        nan,        nan]])
Coordinates:
  * space    (space) float64 0.1 0.2 0.3
  * time     (time) float64 2.5 3.5

如果是沿着numpy.datetime64的坐标插值，可以传字符串：

In [27]:
import pandas as pd
da_dt64 = xr.DataArray(
    [1, 3], [("time", pd.date_range("1/1/2000", "1/3/2000", periods=2))]
)
da_dt64

<xarray.DataArray (time: 2)>
array([1, 3])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-03

In [28]:
da_dt64.interp(time="2000-01-02")

<xarray.DataArray ()>
array(2.)
Coordinates:
    time     datetime64[ns] 2000-01-02

通过指定需要的时间段，可以将新插入的值合并入原始 DataArray 

In [29]:
da_dt64.interp(time=pd.date_range("1/1/2000", "1/3/2000", periods=3))

<xarray.DataArray (time: 3)>
array([1., 2., 3.])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03

如果是在时间范围外插值，则默认插入的是NaN

In [30]:
da_dt64.interp(time="2000-01-04")

<xarray.DataArray ()>
array(nan)
Coordinates:
    time     datetime64[ns] 2000-01-04

如果想要外延插值，则可以进一步利用interpolate_na

In [31]:
da_dt64_new = da_dt64.interp(time=pd.date_range("1/1/2000", "1/4/2000", periods=4))
da_dt64_new

<xarray.DataArray (time: 4)>
array([ 1.,  2.,  3., nan])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [32]:
da_dt64_new.interpolate_na(dim="time",fill_value="extrapolate")

<xarray.DataArray (time: 4)>
array([1., 2., 3., 4.])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

interpolate_na 同样不是 in-place的操作，如果需要更新其值，需要赋值

In [33]:
da_dt64_new

<xarray.DataArray (time: 4)>
array([ 1.,  2.,  3., nan])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [34]:
da_dt64_new_nonan = da_dt64_new.interpolate_na(dim="time",fill_value="extrapolate")
da_dt64_new_nonan

<xarray.DataArray (time: 4)>
array([1., 2., 3., 4.])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

下面是多维数据的情况：

In [35]:
da.interp(time=2.5, space=0.15)

<xarray.DataArray ()>
array(0.60138922)
Coordinates:
    time     float64 2.5
    space    float64 0.15

In [36]:
da.interp(time=[1.5, 2.5], space=[0.15, 0.25])

<xarray.DataArray (time: 2, space: 2)>
array([[0.88810575, 0.86705165],
       [0.60138922, 0.38051172]])
Coordinates:
  * time     (time) float64 1.5 2.5
  * space    (space) float64 0.15 0.25

xarray这些插值函数具体使用的插值方法是 scipy.interpolate.interp1d （一维数据）和 scipy.interpolate.interpn() （多维数据）

下面看看Dataset的插值：

In [37]:
ds = xr.Dataset(
    data_vars={
        "a": ("x", [5, 7, 4]),
        "b": (
            ("x", "y"),
            [[1, 4, 2, 9], [2, 7, 6, np.nan], [6, np.nan, 5, 8]],
        ),
    },
    coords={"x": [0, 1, 2], "y": [10, 12, 14, 16]},
)
ds

<xarray.Dataset>
Dimensions:  (x: 3, y: 4)
Coordinates:
  * x        (x) int32 0 1 2
  * y        (y) int32 10 12 14 16
Data variables:
    a        (x) int32 5 7 4
    b        (x, y) float64 1.0 4.0 2.0 9.0 2.0 7.0 6.0 nan 6.0 nan 5.0 8.0

一维线性插值：

In [38]:
ds.interp(x=[0, 0.75, 1.25, 1.75])

<xarray.Dataset>
Dimensions:  (x: 4, y: 4)
Coordinates:
  * y        (y) int32 10 12 14 16
  * x        (x) float64 0.0 0.75 1.25 1.75
Data variables:
    a        (x) float64 5.0 6.5 6.25 4.75
    b        (x, y) float64 1.0 4.0 2.0 nan 1.75 6.25 ... nan 5.0 nan 5.25 nan

二维插值：

In [39]:
ds.interp(x=[0, 0.75, 1.25, 1.75], y=[11, 13, 15], method="linear")

<xarray.Dataset>
Dimensions:  (x: 4, y: 3)
Coordinates:
  * x        (x) float64 0.0 0.75 1.25 1.75
  * y        (y) int32 11 13 15
Data variables:
    a        (x) float64 5.0 6.5 6.25 4.75
    b        (x, y) float64 2.5 3.0 nan 4.0 5.625 nan nan nan nan nan nan nan

下面看看本文实例数据。补充1996年12月31日的数据。这里选择14303200文件夹下数据为例。

In [40]:
import glob
import os

years = ["1996","1997"]
ens_19961997 = "14303200"
name_lst=[]
for name in glob.glob(os.path.join("gallery-data", ens_19961997,'*.nc')):
    if name.split("_")[1] in years:
        name_lst.append(name)
    # 只要文件名称对应就行了    
ds_19961997 = xr.open_mfdataset(name_lst)
ds_19961997

<xarray.Dataset>
Dimensions:  (time: 730, y: 5, x: 6)
Coordinates:
  * time     (time) datetime64[ns] 1996-01-01T12:00:00 ... 1997-12-31T12:00:00
  * y        (y) float32 548.0 547.0 546.0 545.0 544.0
  * x        (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
Data variables:
    dayl     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    lat      (time, y, x) float64 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    lon      (time, y, x) float64 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    prcp     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    srad     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    swe      (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    tmax     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    tmin     (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
    vp       (time, y, x) float32 dask.array<chunksize=(365, 5, 6), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1996
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

可以看到731天只有730天的数据，1996年12月31日并没有数据，比如取出dayl看一看

In [41]:
ds_19961997.sel(time="1996-12-31")["dayl"].values

array([], shape=(0, 5, 6), dtype=float32)

下面尝试通过指定时间段，插入值并合并入原始 Dataset。因为interp不是inp-place操作，所以需要返回到一个新的dataset中。注意这里是闭区间，periods是pandas date_range的一部分。

另外需要注意原始数据的时间是12点的，所以时间也必须得是12点，否则插值的时候每个时段默认是0点，全部都会插值的，并且由于第一个时段00点在现在的第一个时段12点之前，会插值NaN。

这点要特别注意，所以最好的办法还是将时间构造到12点（也可以使用原数据中的时间，但是比如如果正好最后一个时段在原数据时段外，那么就这样就不行了，不过这里处于方便，暂时就直接这么用了）。

In [42]:
ds_19961997["time"].values[0]

numpy.datetime64('1996-01-01T12:00:00.000000000')

In [43]:
ds_new = ds_19961997.interp(time=pd.date_range(ds_19961997["time"].values[0], ds_19961997["time"].values[-1], periods=731))

In [44]:
ds_new

<xarray.Dataset>
Dimensions:  (time: 731, y: 5, x: 6)
Coordinates:
  * y        (y) float32 548.0 547.0 546.0 545.0 544.0
  * x        (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
  * time     (time) datetime64[ns] 1996-01-01T12:00:00 ... 1997-12-31T12:00:00
Data variables:
    dayl     (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    lat      (time, y, x) float64 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    lon      (time, y, x) float64 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    prcp     (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    srad     (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    swe      (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    tmax     (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    tmin     (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
    vp       (time, y, x) float32 dask.array<chunksize=(731, 5, 6), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1996
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

In [45]:
ds_new.sel(time="1996-12-31")["dayl"].values

array([[[30956.36523438, 30956.36523438, 30956.36523438, 30956.36523438,
         30956.36523438, 30956.36523438],
        [30956.36523438, 30956.36523438, 30956.36523438, 30956.36523438,
         30956.36523438, 30956.36523438],
        [30982.58007812, 30956.36523438, 30956.36523438, 30956.36523438,
         30956.36523438, 30956.36523438],
        [30982.58007812, 30982.58007812, 30982.58007812, 30982.58007812,
         30982.58007812, 30956.36523438],
        [30982.58007812, 30982.58007812, 30982.58007812, 30982.58007812,
         30982.58007812, 30982.58007812]]])

检查一下原来的值是否保持：

In [46]:
ds_new.sel(time="1996-01-01")["dayl"].values == ds_19961997.sel(time="1996-01-01")["dayl"].values

array([[[ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True]]])

## xarray与numpy array 和 pandas dataframe 的转换

xarray的数据是懒加载地，通常我们还是需要把数据取出来用，有时候需要将数据转换为pandas DataFrame或者numpy array或者torch的tensor等。

比如想要取出 dayl, prcp 的值，并组成一个numpy array

In [47]:
import os
import glob
import pandas as pd
import xarray as xr
years = ["1990","1991"]
dir_list = ["14303200","14306340"]
ens_list_19901991 = []
for num in range(len(dir_list)):
    ens_19901991 = dir_list[num]
    name_lst=[]
    for name in glob.glob(os.path.join("gallery-data", ens_19901991,'*.nc')):
        if name.split("_")[1] in years:
            name_lst.append(name)
    # 只要文件名称对应就行了    
    ens_list_19901991.append(xr.open_mfdataset(name_lst))
# dim的值如果是新维度，会增加到第一个维度上
new_dim = pd.Index(dir_list)
ds_19901991 = xr.concat(ens_list_19901991, dim=new_dim)

In [48]:
ds_19901991[['dayl', 'prcp']]

<xarray.Dataset>
Dimensions:     (concat_dim: 2, time: 730, y: 11, x: 13)
Coordinates:
  * y           (y) float64 437.0 438.0 439.0 440.0 ... 545.0 546.0 547.0 548.0
  * x           (x) float64 -1.776e+03 -1.775e+03 ... -1.735e+03 -1.734e+03
  * time        (time) datetime64[ns] 1990-01-01T12:00:00 ... 1991-12-31T12:0...
  * concat_dim  (concat_dim) object '14303200' '14306340'
Data variables:
    dayl        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
    prcp        (concat_dim, time, y, x) float32 dask.array<chunksize=(1, 365, 11, 13), meta=np.ndarray>
Attributes: (12/17)
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    ...                  ...
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

比较直接的方法是新建一个ndarray，然后依次放入dataset中的数据到ndarray中。要注意尺寸大小要能对上

In [49]:
# 检查数据的尺寸
ds_19901991["dayl"].shape

(2, 730, 11, 13)

In [50]:
# 或者每个坐标检查尺寸：
ds_19901991.x.shape

(13,)

In [51]:
# 或者用dims属性检查
ds_19901991.dims

Frozen({'y': 11, 'x': 13, 'concat_dim': 2, 'time': 730})

In [52]:
ds_19901991._dims

{'y': 11, 'x': 13, 'concat_dim': 2, 'time': 730}

不过为了保险起见，还是直接使用最前面的第一种方式较好。

In [53]:
import numpy as np

arr = np.zeros([2]+list(ds_19901991["dayl"].shape))
for i in range(len(['dayl', 'prcp'])):
    arr[i] = ds_19901991[['dayl', 'prcp'][i]].values
type(arr)

numpy.ndarray

In [54]:
arr.shape

(2, 2, 730, 11, 13)

另外一种直接一点的方式是dataset转成dataarray，不过这种方式实践中不是很直观好用，所以仅供参考。

此数据集的数据变量将相互广播并沿新数组的第一个轴堆叠。此数据集的所有坐标将保持。

In [55]:
ds_trans_origin = ens_list[0]

In [56]:
ds_dataarray = ds_trans_origin[['dayl', 'prcp']].to_array()

In [57]:
ds_dataarray

<xarray.DataArray 'stack-48dd347ca7c08914914f5255404c7166' (variable: 2,
                                                            time: 1825, y: 5,
                                                            x: 6)>
dask.array<stack, shape=(2, 1825, 5, 6), dtype=float32, chunksize=(1, 365, 5, 6), chunktype=numpy.ndarray>
Coordinates:
  * time      (time) datetime64[ns] 1990-01-01T12:00:00 ... 1997-12-31T12:00:00
  * y         (y) float32 548.0 547.0 546.0 545.0 544.0
  * x         (x) float32 -1.739e+03 -1.738e+03 ... -1.735e+03 -1.734e+03
  * variable  (variable) <U4 'dayl' 'prcp'
Attributes:
    start_year:          1990
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.29512059384709
    geospatial_lat_max:  45.35616846337259
    geospatial_lon_min:  -123.57965629352381
    geospatial_lon_max:  -123.48399519568804
    crs:                 +proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-10...
    nodatavals:          -9999
    transform:           [ 1.00000e+00  0.00000e+00 -1.73975e+03  0.00000e+00...
    res:                 [1. 1.]
    bounds:              [-1739.75   543.5  -1733.75   548.5 ]

dataarray可以转成numpy的array，直接取values即可。可以看到维度是保持顺序的。

In [58]:
ds_dataarray.values.shape

(2, 1825, 5, 6)

当选择的变量对应的数据的维度一致时，可以直接转为dataframe

In [59]:
ds_trans_origin[['dayl', 'prcp']].to_dataframe()

dayl   prcp
time                y     x                            
1990-01-01 12:00:00 548.0 -1739.25  30980.070312  15.50
                          -1738.25  30980.070312  15.24
                          -1737.25  30980.070312  14.61
                          -1736.25  30980.070312  14.44
                          -1735.25  30980.070312  14.65
...                                          ...    ...
1997-12-31 12:00:00 544.0 -1738.25  30958.929688  12.34
                          -1737.25  30958.929688  12.20
                          -1736.25  30958.929688  11.70
                          -1735.25  30958.929688  11.38
                          -1734.25  30958.929688  11.26

[54750 rows x 2 columns]

和 DataFrame的转换就比较简单了，xarray 的 dataset 和 pandas 的DataFrame 是相似的，有直接的函数 [xarray.Dataset.to_dataframe](https://xarray.pydata.org/en/v0.11.3/generated/xarray.Dataset.to_dataframe.html)

In [60]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand( 4,3), columns=list('mno'),
                  index=pd.date_range(start='2000', periods=4, name='date'))
df

m         n         o
date                                    
2000-01-01  0.252164  0.585237  0.998131
2000-01-02  0.198527  0.529427  0.598019
2000-01-03  0.043518  0.422307  0.685340
2000-01-04  0.339274  0.057494  0.257945

In [61]:
import xarray as xr
dataset_df = xr.Dataset(df)
dataset_df

<xarray.Dataset>
Dimensions:  (date: 4)
Coordinates:
  * date     (date) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
Data variables:
    m        (date) float64 0.2522 0.1985 0.04352 0.3393
    n        (date) float64 0.5852 0.5294 0.4223 0.05749
    o        (date) float64 0.9981 0.598 0.6853 0.2579

In [62]:
dataset_df.to_dataframe()

m         n         o
date                                    
2000-01-01  0.252164  0.585237  0.998131
2000-01-02  0.198527  0.529427  0.598019
2000-01-03  0.043518  0.422307  0.685340
2000-01-04  0.339274  0.057494  0.257945

## DataArray基本运算

对 xarray 中 DataArray做计算时, 默认的是按照维度名字匹配的, 这里以乘法为例，看下面的例子.

In [63]:
import xarray as xr
x = xr.DataArray(
     [[1.0, 2.0], [3.0, 5.0]],
     dims=("lat", "lon"),
     coords={"lat": [35.0, 40.0], "lon": [100.0, 120.0]},
     name="var1",
)
x

<xarray.DataArray 'var1' (lat: 2, lon: 2)>
array([[1., 2.],
       [3., 5.]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0

In [64]:
t = xr.DataArray([0.1,0.2,0.3], dims="time", coords={"time": [1, 2, 3]}, name="var2")
t

<xarray.DataArray 'var2' (time: 3)>
array([0.1, 0.2, 0.3])
Coordinates:
  * time     (time) int32 1 2 3

In [65]:
y = x * t
y

<xarray.DataArray (lat: 2, lon: 2, time: 3)>
array([[[0.1, 0.2, 0.3],
        [0.2, 0.4, 0.6]],

       [[0.3, 0.6, 0.9],
        [0.5, 1. , 1.5]]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0
  * time     (time) int32 1 2 3

可以看到上述计算中, 乘积是执行的笛卡尔积, 因为没有维度对应上. 再看一个例子

In [66]:
z = x * y
z

<xarray.DataArray (lat: 2, lon: 2, time: 3)>
array([[[0.1, 0.2, 0.3],
        [0.4, 0.8, 1.2]],

       [[0.9, 1.8, 2.7],
        [2.5, 5. , 7.5]]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0
  * time     (time) int32 1 2 3

In [67]:
x

<xarray.DataArray 'var1' (lat: 2, lon: 2)>
array([[1., 2.],
       [3., 5.]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0

可以看到, lat和lon一致的地方对应相乘; 关于时间维, 相当于在x上执行了广播运算. 也就是说相当于 x * y.isel(time=0),  x * y.isel(time=1),  x * y.isel(time=2)

In [68]:
x * y.isel(time=0)

<xarray.DataArray (lat: 2, lon: 2)>
array([[0.1, 0.4],
       [0.9, 2.5]])
Coordinates:
  * lat      (lat) float64 35.0 40.0
  * lon      (lon) float64 100.0 120.0
    time     int32 1